[W-10592536] add current version indicator
mulesoft/docs-site-ui pull request #203
Opened 2022-10-11 19:12 UTC by cheungaryk

ref: W-10592536

- add a blue dot indicator for the current version in the left nav version selector. The indicator has a tooltip that tells users what it means
- upgrade a library called tippy.js to the latest version

https://www.loom.com/share/5a84587a82384ae79d23a282f70fb259

2022-10-13 23:12 UTC, sanderson-sfdc requested changes

2022-10-13 23:12 UTC, sanderson-sfdc commented on src/js/01-nav.js
> +      content: 'This is the latest version.',
This should be in a labels file so we can get this translated into Japanese.

2022-10-13 23:12 UTC, sanderson-sfdc commented on src/partials/notice-banner.hbs
> +      <button class="notice-banner-close-button" title="Close the notice banner">&times;</button>
I know I'm being picky on this, but we should move this to a labels file, too.  

I'm sure we have other strings that aren't properly translated, but we should do this properly anyway.

2022-10-13 23:12 UTC, sanderson-sfdc commented on src/partials/notice-banner.hbs
>        <p>This version of the product has reached
I know you didn't change this, but since it's close to the new work, maybe you could move this into a labels file, too.

2022-10-14 15:42 UTC, cheungaryk commented
@sanderson-sfdc I know that we have an initiative to merge the Eng and JP UI bundles (which is actually like 70% done in #195 but in a blocked state for 2 more weeks), but it feels out of scope for this ticket and was never communicated as a requirement prior.

My response is to create a new user story for separating out the languages in a label file (is it the same as a map?), and then probably add the work to #195.

2022-10-14 16:18 UTC, sanderson-sfdc commented
That's the right action, @cheungaryk , thanks for doing that.  I should have created the story instead of adding a requirement here.

2022-10-14 16:44 UTC, merged